### ISSUE TITLE
`{astgrepr}` can't be installed on R 4.0

### ISSUE THREAD

**Issue by IndrajeetPatil** [etiennebacher/astgrepr#28]
Here is what I see on `R 4.0.3`:

```r
> pak::pkg_install("etiennebacher/flint")
✔ Updated metadata database: 1.96 MB in 2 files.                          
✔ Updating metadata database ... done                                     
                                                                            
→ Will install 2 packages.
→ All 2 packages (0 B) are cached.
+ astgrepr   0.0.6      [bld][cmp] (GitHub: 4e5e241) + ✔ rustc, ✔ cargo
+ flint      0.0.3.9000 [bld][cmp] (GitHub: f91c785)
✔ All system requirements are already installed.
  
ℹ No downloads are needed, 2 pkgs are cached
ℹ Building astgrepr 0.0.6
✖ Failed to build astgrepr 0.0.6 (44s)                            
Error:                                                            
! error in pak subprocess
Caused by error in `stop_task_build(state, worker)`:
! Failed to build source package astgrepr.
Full installation output:
* installing *source* package 'astgrepr' ...
staged installation is only possible with locking
** using non-staged installation
** libs
rm -Rf astgrepr.so ./rust/target/release/libastgrepr.a entrypoint.o /tmp/RtmpRgdx7u/R.INSTALL1ae525e0ee11/astgrepr/src/.cargo /tmp/RtmpRgdx7u/R.INSTALL1ae525e0ee11/astgrepr/src/vendor
gcc -I"/opt/R/4.0.3/lib/R/include" -DNDEBUG   -I/usr/local/include   -fpic  -g -O2  -Wall -pedantic -fdiagnostics-color=always -c entrypoint.c -o entrypoint.o
if [ -f ./rust/vendor.tar.xz ]; then \
	tar xf rust/vendor.tar.xz && \
	mkdir -p /tmp/RtmpRgdx7u/R.INSTALL1ae525e0ee11/astgrepr/src/.cargo && \
	cp rust/vendor-config.toml /tmp/RtmpRgdx7u/R.INSTALL1ae525e0ee11/astgrepr/src/.cargo/config.toml; \
fi
# In some environments, ~/.cargo/bin might not be included in PATH, so we need
# to set it here to ensure cargo can be invoked. It is appended to PATH and
# therefore is only used if cargo is absent from the user's PATH.
if [ "" != "true" ]; then \
	export CARGO_HOME=/tmp/RtmpRgdx7u/R.INSTALL1ae525e0ee11/astgrepr/src/.cargo; \
fi && \
	export PATH="/home/indra/Documents/vx/.venv/bin:/home/indra/google-cloud-sdk/bin:/home/indra/.pyenv/shims:/home/indra/.pyenv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin:/usr/lib/rstudio/resources/app/bin/quarto/bin:/usr/lib/rstudio/resources/app/bin/postback:/home/indra/.cargo/bin" && \
		cargo build -j 2 --offline --lib --release --manifest-path=./rust/Cargo.toml --target-dir ./rust/target && \
		echo `cargo --version` && echo `rustc --version`;
   Compiling proc-macro2 v1.0.79
   Compiling unicode-ident v1.0.12
   Compiling memchr v2.7.2
   Compiling quote v1.0.35
   Compiling cc v1.0.99
   Compiling syn v2.0.57
   Compiling wasm-bindgen-shared v0.2.92
   Compiling aho-corasick v1.1.3
   Compiling regex-syntax v0.8.3
   Compiling tree-sitter v0.21.0
   Compiling once_cell v1.19.0
   Compiling log v0.4.21
   Compiling bumpalo v3.15.4
   Compiling wasm-bindgen-backend v0.2.92
   Compiling regex-automata v0.4.6
   Compiling serde v1.0.203
   Compiling regex v1.10.4
   Compiling wasm-bindgen-macro-support v0.2.92
   Compiling serde_derive v1.0.203
   Compiling wasm-bindgen v0.2.92
   Compiling wasm-bindgen-macro v0.2.92
   Compiling serde_json v1.0.115
   Compiling cfg-if v1.0.0
   Compiling libR-sys v0.7.0
   Compiling thiserror v1.0.61
   Compiling ryu v1.0.17
   Compiling itoa v1.0.11
   Compiling thiserror-impl v1.0.61
   Compiling serde_derive_internals v0.29.1
   Compiling schemars v0.8.21
   Compiling hashbrown v0.14.3
   Compiling equivalent v1.0.1
   Compiling paste v1.0.14
   Compiling anyhow v1.0.86
   Compiling bit-vec v0.7.0
   Compiling indexmap v2.2.6
   Compiling bit-set v0.6.0
   Compiling schemars_derive v0.8.21
   Compiling tree-sitter-facade-sg v0.21.5
   Compiling tree-sitter-r v1.0.1
   Compiling bstr v1.9.1
   Compiling unsafe-libyaml v0.2.11
   Compiling dyn-clone v1.0.17
   Compiling extendr-api v0.7.0
   Compiling globset v0.4.14
   Compiling serde_yaml v0.9.34+deprecated
   Compiling ast-grep-core v0.25.0
   Compiling extendr-macros v0.7.0
   Compiling ast-grep-config v0.25.0
error[E0425]: cannot find value `S4SXP` in this scope
   --> /tmp/RtmpRgdx7u/R.INSTALL1ae525e0ee11/astgrepr/src/vendor/extendr-api/src/lib.rs:574:15
    |
574 |         S4 => S4SXP,
    |               ^^^^^ not found in this scope

For more information about this error, try `rustc --explain E0425`.
error: could not compile `extendr-api` (lib) due to previous error
warning: build failed, waiting for other jobs to finish...
make: *** [Makevars:19: rust/target/release/libastgrepr.a] Error 101
ERROR: compilation failed for package 'astgrepr'
* removing '/tmp/RtmpowTQQz/pkg-lib1adf1db31935/astgrepr'
```

**Comment by etiennebacher** [comment]
Yes I think `extendr`-based packages require R >= 4.3. I'll double check

**Comment by IndrajeetPatil** [comment]
If that is indeed the case, it will be nice to set a minimum required version in `DESCRIPTION` because, otherwise, users on `R < 4.3` are going to be confused about the error message (`cannot find value S4SXP in this scope`).

Thanks.

**Comment by etiennebacher** [comment]
Compilation only works with R >= 4.2. I don't want to play with the various features provided by `extendr` so I put this version requirement in DESCRIPTION and I added CI workflows for this. Thanks for the report @IndrajeetPatil
